export const TODO_ACTIONS = {
    ADD_TODO: "ADD_TODO",
    REMOVE_TODO: "REMOVE_TODO",
    COMPLETE_TODO: "COMPLETE_TODO"
}

export const TODO_STATUS = {
    COMPLETE: 'COMPLETE',
    INCOMPLETE: 'INCOMPLETE'
}